---
- name: Setup Git Configs
  hosts: localhost
  
  tasks: 
  - name: Setup SSH Configs
    file:
      src: "~/setup-my-machines/files/ssh/config_ed"
      dest: "~/.ssh/config"
      state: link
      force: true
      follow: false
